name: Daily Bible Reading

on:
  workflow_dispatch:

jobs:
  send-bible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Send Bible Reading
        env:
          BIBLE_TELEGRAM_BOT_TOKEN: ${{ secrets.BIBLE_TELEGRAM_BOT_TOKEN }}
          BIBLE_CHANNEL_ID: ${{ secrets.BIBLE_CHANNEL_ID }}
        run: |
          pip install requests -q
          python3 bible.py
